#!/bin/bash
echo '#!/bin/bash' > 0-hello_world
echo '#!/bin/bash' > 1-confused_smiley
echo '#!/bin/bash' > 2-hellofile
echo '#!/bin/bash' > 3-twofiles
echo '#!/bin/bash' > 4-lastlines
echo '#!/bin/bash' > 5-firstlines
echo '#!/bin/bash' > 6-third_line
echo '#!/bin/bash' > 7-file
echo '#!/bin/bash' > 8-cwd_state
echo '#!/bin/bash' > 9-duplicate_last_line
echo '#!/bin/bash' > 10-no_more_js
echo '#!/bin/bash' > 11-directories
echo '#!/bin/bash' > 12-newest_files
echo '#!/bin/bash' > 13-unique
echo '#!/bin/bash' > 14-findthatword
echo '#!/bin/bash' > 15-countthatword
echo '#!/bin/bash' > 17-hidethisword
echo '#!/bin/bash' > 18-letteronly
echo '#!/bin/bash' > 19-AZ
echo '#!/bin/bash' > 20-hiago
echo '#!/bin/bash' > 21-reverse
echo '#!/bin/bash' > 22-users_and_homes
echo '#!/bin/bash' > 100-empty_casks
echo '#!/bin/bash' > 101-gifs
echo '#!/bin/bash' > 102-acrostic
echo '#!/bin/bash' > 103-the_biggest_fan
chmod u+x *
chmod u-x README.md
echo "echo 'Hello, World'" >> 0-hello_world
echo "echo '\"(Ôo)\''" >> 1-confused_smiley
echo "cat /etc/passwd" >> 2-hellofile
echo "cat /etc/passwd /etc/hosts" >> 3-twofiles
echo "tail -n 10 /etc/passwd" >> 4-lastlines
echo "head -n 10 /etc/passwd" >> 5-firstlines
echo "sed -n '3p' iacta" >> 6-third_line
echo "ls -la > ls_cwd_content" >> 8-cwd_state
echo "tail -n 1 iacta >> iacta" >> 9-duplicate_last_line
echo "find . -name '*.js' -delete" >> 10-no_more_js
echo "find . -type d | wc -l" >> 11-directories
echo "ls -Art | tail -n 10" >> 12-newest_files
echo "sort | uniq -u" >> 13-unique
echo "cat /etc/passwd | grep 'root'" >> 14-findthatword
echo "grep -r 'bin' /etc/passwd | wc -l" >> 15-countthatword
echo "grep -B 4 'root' /etc/passwd" >> 16-whatsnext
echo "grep -L "bin" /etc/passwd" >> 17-hidethisword
echo "grep '^[[:alpha:]]' /etc/ssh/sshd_config" >> 18-letteronly
echo "tr Ac Ze" >> 19-AZ
echo "tr -d cC" >> 20-hiago
echo "rev" >> 21-reverse

